name: XG7RandomKits
version: '${project.version}'
main: com.xg7network.xg7randomkits.XG7RandomKits
api-version: '1.16'
softdepend: [PlaceholderAPI]
authors: [DaviXG7]
description: Better random kits plugin
website: www.xg7network.com

commands:
  xg7rkregion:
    description: "RandomKits region manager"
    usage: "/<command> [save, set, check, delete]"
    aliases:
      - 7rkregion
      - rkregion

permissions:
  xg7rk.admin:

    default: op
    description: Administradores do plugin
    children:
      xg7rk.region.*: true


  xg7rk.region.*:
    default: op
    description: Permissões de região
    children:
      xg7rk.region.set: true
      xg7rk.region.check: true
      xg7rk.region.delete: true
      xg7rk.region.reset: true
